// SQL of this component, one named query per statement. Domain code passes the executor: the pool,
// or the connection of a transaction it has opened.
import type {RowDataPacket} from 'mysql2/promise';
import type {Executor,SqlValue} from '../../../libraries/db.js';
export function insertIgnoreChatMessages(c:Executor,params:SqlValue[]){return c.execute("INSERT IGNORE INTO ai_chat_messages(account_id,session_id,customer,message_id,direction,origin,type,text) VALUES (?,?,?,?,'in','customer',?,?)",params);}
export function selectChatMessagesCustomerByAccountIdSessionIdMessageId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>("SELECT customer FROM ai_chat_messages WHERE account_id=? AND session_id=? AND message_id=? AND direction='out' AND (status IS NULL OR FIELD(status,'sent','delivered','read')<FIELD(?,'sent','delivered','read'))",params);}
export function updateChatMessagesStatusByAccountIdSessionIdMessageId(c:Executor,params:SqlValue[]){return c.execute("UPDATE ai_chat_messages SET status=? WHERE account_id=? AND session_id=? AND message_id=? AND (status IS NULL OR FIELD(status,'sent','delivered','read')<FIELD(?,'sent','delivered','read'))",params);}
export function selectChatMessagesByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>("SELECT customer,text,direction,origin,type,created_at FROM (SELECT customer,text,direction,origin,type,created_at,ROW_NUMBER() OVER (PARTITION BY customer ORDER BY created_at DESC,message_id DESC) AS n FROM ai_chat_messages WHERE account_id=? AND session_id=? AND direction<>'note') t WHERE n=1",params);}
export function selectConversationsByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT customer,paused,full_auto,JSON_LENGTH(messages) AS message_count,router_context FROM ai_conversations WHERE account_id=? AND session_id=?',params);}
export function selectChatMessagesByAccountIdSessionIdCustomer(c:Executor,params:SqlValue[],cursor:[Date, string] | undefined){return c.execute<RowDataPacket[]>('SELECT message_id,direction,origin,type,text,status,created_at FROM ai_chat_messages WHERE account_id=? AND session_id=? AND customer=?'+(cursor?' AND (created_at<? OR (created_at=? AND message_id<?))':'')+' ORDER BY created_at DESC,message_id DESC LIMIT 101',params);}

export function upsertChatMessages(c:Executor,params:SqlValue[]){return c.execute("INSERT INTO ai_chat_messages(account_id,session_id,customer,message_id,direction,origin,type,text,status) VALUES (?,?,?,?,'out',?,?,?,'sent') ON DUPLICATE KEY UPDATE origin=IF(VALUES(origin)='api',origin,VALUES(origin))",params);}
export function insertChatMessages(c:Executor,params:SqlValue[]){return c.execute("INSERT INTO ai_chat_messages(account_id,session_id,customer,message_id,direction,origin,text) VALUES (?,?,?,?,'note','system',?)",params);}
