// SQL of this component, one named query per statement. Domain code passes the executor: the pool,
// or the connection of a transaction it has opened.
import type {RowDataPacket} from 'mysql2/promise';
import type {Executor,SqlValue} from '../../../libraries/db.js';
export function selectAssistantsByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT a.session_id,a.enabled,p.id,p.name,p.profile_type FROM ai_assistants a LEFT JOIN ai_data_profiles p ON p.id=a.data_profile_id WHERE a.account_id=?',params);}
export function upsertAssistantEnabled(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_assistants(account_id,session_id,enabled) VALUES (?,?,?) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled),revision=revision+1',params);}
export function lockAssistantsDataProfileIdByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT data_profile_id FROM ai_assistants WHERE account_id=? AND session_id=? FOR UPDATE',params);}
export function attachNewDataProfile(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_assistants(account_id,session_id,enabled,data_profile_id) VALUES (?,?,FALSE,?) ON DUPLICATE KEY UPDATE data_profile_id=VALUES(data_profile_id),revision=revision+1',params);}
export function lockDataProfilesNameByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT name FROM ai_data_profiles WHERE account_id=? FOR UPDATE',params);}
export function countDataProfilesByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT COUNT(*) AS n FROM ai_data_profiles WHERE account_id=?',params);}
export function insertDataProfiles(c:Executor,params:SqlValue[],columns:string[],edu:{ edu_lembaga: string; edu_jadwal: string; }){return c.execute(`INSERT INTO ai_data_profiles(id,account_id,profile_type,name,behavior,fallback_number,fallback_notify,${columns.join(',')},${Object.keys(edu).join(',')}) VALUES (?,?,?,?,?,?,?,${columns.map(()=>'?').join(',')},${Object.keys(edu).map(()=>'?').join(',')})`,params);}
export function selectAssistantsDataProfileIdByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT data_profile_id FROM ai_assistants WHERE account_id=? AND session_id=?',params);}
export function selectDataProfilesIdByIdAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM ai_data_profiles WHERE id=? AND account_id=?',params);}
export function selectDataProfilesProfileTypeByIdAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT profile_type FROM ai_data_profiles WHERE id=? AND account_id=?',params);}
export function selectProducts(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT p.id,p.profile_type,p.name,p.updated_at,(SELECT COUNT(*) FROM ai_products x WHERE x.data_profile_id=p.id) AS products,(SELECT COUNT(*) FROM ai_orders o WHERE o.data_profile_id=p.id) AS orders,(SELECT COUNT(*) FROM ai_edu_programs e WHERE e.data_profile_id=p.id) AS programs,(SELECT COUNT(*) FROM ai_edu_documents e WHERE e.data_profile_id=p.id) AS documents,(SELECT COUNT(*) FROM ai_edu_contacts e WHERE e.data_profile_id=p.id) AS contacts FROM ai_data_profiles p WHERE p.account_id=? ORDER BY p.name',params);}
export function selectAssistantsDataProfileIdSessionIdByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT data_profile_id,session_id FROM ai_assistants WHERE account_id=? AND data_profile_id IS NOT NULL ORDER BY session_id',params);}
export function selectDataProfilesByIdAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM ai_data_profiles WHERE id=? AND account_id=?',params);}
export function selectAssistantsSessionIdByAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT session_id FROM ai_assistants WHERE account_id=? AND data_profile_id=? ORDER BY session_id',params);}
export function shareDataProfileRow(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM ai_data_profiles WHERE id=? AND account_id=? FOR SHARE',params);}
export function lockDataProfilesIdByAccountIdName(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM ai_data_profiles WHERE account_id=? AND name=? FOR UPDATE',params);}
export function selectProductImagesIdByAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM ai_product_images WHERE account_id=? AND data_profile_id=?',params);}
export function insertProductImages(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_product_images(id,account_id,data_profile_id,size_bytes) VALUES (?,?,?,?)',params);}
export function selectProductsByAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM ai_products WHERE account_id=? AND data_profile_id=?',params);}
export function insertProducts(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_products(account_id,data_profile_id,name,type,description,price,stock,active,image_id) VALUES (?,?,?,?,?,?,?,?,?)',params);}
export function insertDataSources(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_data_sources(account_id,data_profile_id,kind,mode,endpoint,secret) SELECT account_id,?,kind,mode,endpoint,secret FROM ai_data_sources WHERE account_id=? AND data_profile_id=?',params);}
export function lockDataProfilesIdByIdAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM ai_data_profiles WHERE id=? AND account_id=? FOR UPDATE',params);}
export function selectDataProfilesIdByAccountIdNameId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM ai_data_profiles WHERE account_id=? AND name=? AND id<>?',params);}
export function updateDataProfilesNameById(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_data_profiles SET name=? WHERE id=?',params);}
export function lockAssistantsSessionIdByAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT session_id FROM ai_assistants WHERE account_id=? AND data_profile_id=? FOR UPDATE',params);}
export function deleteDataProfilesByIdAccountId(c:Executor,params:SqlValue[]){return c.execute('DELETE FROM ai_data_profiles WHERE id=? AND account_id=?',params);}
export function shareDataProfileSummary(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,name,profile_type FROM ai_data_profiles WHERE id=? AND account_id=? FOR SHARE',params);}
export function lockAssistantsDataProfileIdEnabledByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT data_profile_id,enabled FROM ai_assistants WHERE account_id=? AND session_id=? FOR UPDATE',params);}
export function upsertAssistantProfile(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_assistants(account_id,session_id,enabled,data_profile_id) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled),data_profile_id=VALUES(data_profile_id),revision=revision+1',params);}
export function lockConversationsCustomerByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT customer FROM ai_conversations WHERE account_id=? AND session_id=? FOR UPDATE',params);}
export function updateConversationsMessagesByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_conversations SET messages=JSON_ARRAY(),router_context=NULL,revision=revision+1 WHERE account_id=? AND session_id=?',params);}
export function updateDataProfilesXByIdAccountId(c:Executor,params:SqlValue[],spec:{ readonly column: "edu_lembaga"; readonly max: 4000; readonly label: "Profil lembaga"; } | { readonly column: "edu_jadwal"; readonly max: 8000; readonly label: "Jadwal"; }){return c.execute(`UPDATE ai_data_profiles SET ${spec.column}=?,revision=revision+1 WHERE id=? AND account_id=?`,params);}
export function updateDataProfilesProfilByIdAccountId(c:Executor,params:SqlValue[],field:string){return c.execute(`UPDATE ai_data_profiles SET profil_${field}=?,revision=revision+1 WHERE id=? AND account_id=?`,params);}
export function updateDataProfileBehavior(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_data_profiles SET behavior=?,revision=revision+1 WHERE id=? AND account_id=?',params);}
export function selectDataProfilesFallbackNumberFallbackNotifyByIdAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT fallback_number,fallback_notify FROM ai_data_profiles WHERE id=? AND account_id=?',params);}
export function updateDataProfilesFallbackNumberByIdAccountId(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_data_profiles SET fallback_number=?,fallback_notify=?,revision=revision+1 WHERE id=? AND account_id=?',params);}
export function selectAssistantsByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT a.enabled,a.data_profile_id,p.* FROM ai_assistants a LEFT JOIN ai_data_profiles p ON p.id=a.data_profile_id WHERE a.account_id=? AND a.session_id=?',params);}
export function selectDataProfilesProfileTypeById(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT profile_type FROM ai_data_profiles WHERE id=?',params);}
export function updateDataProfileContent(c:Executor,params:SqlValue[],profileColumns:string[]){return c.execute(`UPDATE ai_data_profiles SET behavior=?,fallback_number=?,fallback_notify=?,revision=revision+1,${profileColumns.map(column=>column+'=?').join(',')} WHERE id=? AND account_id=?`,params);}
export function updateAssistantsEnabledByAccountIdSessionId(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_assistants SET enabled=?,revision=revision+1 WHERE account_id=? AND session_id=?',params);}
