// SQL of this component, one named query per statement. Domain code passes the executor: the pool,
// or the connection of a transaction it has opened.
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import type {Executor,SqlValue} from '../../../libraries/db.js';
export function selectEduProgramsByAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,name,description FROM ai_edu_programs WHERE account_id=? AND data_profile_id=? ORDER BY position,created_at,id',params);}
export function selectEduProgramsIdByDataProfileIdNameId(c:Executor,params:SqlValue[],id:string | null){return c.execute<RowDataPacket[]>('SELECT id FROM ai_edu_programs WHERE data_profile_id=? AND name=?'+(id?' AND id<>?':''),params);}
export function updateEduProgramsNameByIdAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<ResultSetHeader>('UPDATE ai_edu_programs SET name=?,description=? WHERE id=? AND account_id=? AND data_profile_id=?',params);}
export function countEduProgramsByDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT COUNT(*) AS n,COALESCE(MAX(position),0) AS last FROM ai_edu_programs WHERE data_profile_id=?',params);}
export function insertEduProgram(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_edu_programs(id,account_id,data_profile_id,name,description,position) VALUES (?,?,?,?,?,?)',params);}
export function deleteEduProgramsByIdAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<ResultSetHeader>('DELETE FROM ai_edu_programs WHERE id=? AND account_id=? AND data_profile_id=?',params);}
export function selectEduContactsByAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,bagian,kontak,deskripsi FROM ai_edu_contacts WHERE account_id=? AND data_profile_id=? ORDER BY position,created_at,id',params);}
export function updateEduContactsBagianByIdAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<ResultSetHeader>('UPDATE ai_edu_contacts SET bagian=?,kontak=?,deskripsi=? WHERE id=? AND account_id=? AND data_profile_id=?',params);}
export function countEduContactsByDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT COUNT(*) AS n,COALESCE(MAX(position),0) AS last FROM ai_edu_contacts WHERE data_profile_id=?',params);}
export function insertEduContact(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_edu_contacts(id,account_id,data_profile_id,bagian,kontak,deskripsi,position) VALUES (?,?,?,?,?,?,?)',params);}
export function deleteEduContactsByIdAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<ResultSetHeader>('DELETE FROM ai_edu_contacts WHERE id=? AND account_id=? AND data_profile_id=?',params);}
export function selectEduDocuments(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,filename,mimetype,media_type,size_bytes,description,created_at FROM ai_edu_documents WHERE account_id=? AND data_profile_id=? ORDER BY position,created_at,id',params);}
export function countEduDocumentsByDataProfileIdId(c:Executor,params:SqlValue[],replacing:string | undefined){return c.execute<RowDataPacket[]>('SELECT COUNT(*) AS n,COALESCE(SUM(size_bytes),0) AS bytes,COALESCE(MAX(position),0) AS last FROM ai_edu_documents WHERE data_profile_id=?'+(replacing?' AND id<>?':''),params);}
export function insertEduDocuments(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_edu_documents(id,account_id,data_profile_id,filename,mimetype,media_type,size_bytes,description,position) VALUES (?,?,?,?,?,?,?,?,?)',params);}
export function lockEduDocumentsFileIdByIdAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT file_id FROM ai_edu_documents WHERE id=? AND account_id=? AND data_profile_id=? FOR UPDATE',params);}
export function updateEduDocumentsFileIdById(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_edu_documents SET file_id=?,filename=?,mimetype=?,media_type=?,size_bytes=? WHERE id=?',params);}
export function updateEduDocumentsDescriptionByIdAccountIdDataProfileId(c:Executor,params:SqlValue[]){return c.execute<ResultSetHeader>('UPDATE ai_edu_documents SET description=? WHERE id=? AND account_id=? AND data_profile_id=?',params);}
export function deleteEduDocumentsById(c:Executor,params:SqlValue[]){return c.execute('DELETE FROM ai_edu_documents WHERE id=?',params);}
export function selectEduDocumentsByIdAccountIdDataProfileId(c:Executor,params:SqlValue[],profile:string | undefined){return c.execute<RowDataPacket[]>('SELECT id,file_id,filename,mimetype,media_type FROM ai_edu_documents WHERE id=? AND account_id=?'+(profile?' AND data_profile_id=?':''),params);}
export function copyEduPrograms(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_edu_programs(id,account_id,data_profile_id,name,description,position) SELECT UUID(),account_id,?,name,description,position FROM ai_edu_programs WHERE account_id=? AND data_profile_id=?',params);}
export function copyEduContacts(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_edu_contacts(id,account_id,data_profile_id,bagian,kontak,deskripsi,position) SELECT UUID(),account_id,?,bagian,kontak,deskripsi,position FROM ai_edu_contacts WHERE account_id=? AND data_profile_id=?',params);}
export function selectEduDocumentRowsForCopy(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM ai_edu_documents WHERE account_id=? AND data_profile_id=? ORDER BY position',params);}
export function selectEduDocumentFiles(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT COALESCE(file_id,id) AS file FROM ai_edu_documents WHERE account_id=? AND data_profile_id=?',params);}
export function lockAccountsSuspendedById(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT suspended FROM accounts WHERE id=? FOR UPDATE',params);}
export function lockDataProfilesProfileTypeByIdAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT profile_type FROM ai_data_profiles WHERE id=? AND account_id=? FOR UPDATE',params);}
export function updateDataProfilesRevisionById(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_data_profiles SET revision=revision+1 WHERE id=?',params);}
export function selectDataProfilesByIdAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>("SELECT edu_lembaga,edu_jadwal,profil_faq FROM ai_data_profiles WHERE id=? AND account_id=? AND profile_type='pendidikan'",params);}
