// SQL of this component, one named query per statement. Domain code passes the executor: the pool,
// or the connection of a transaction it has opened.
import type {RowDataPacket} from 'mysql2/promise';
import type {Executor,SqlValue} from '../../../libraries/db.js';
export function lockUsageByAccountId(c:Executor,params:SqlValue[],account:string | undefined){return c.execute<RowDataPacket[]>("SELECT account_id,request_id,reserved FROM ai_usage WHERE status='generating'"+(account?' AND account_id=?':'')+' FOR UPDATE',params);}
export function markUsageInterrupted(c:Executor,params:SqlValue[]){return c.execute("UPDATE ai_usage SET status='interrupted',reserved=0 WHERE account_id=? AND request_id=?",params);}
export function updateUsageStatusByAccountId(c:Executor,params:SqlValue[],account:string | undefined){return c.execute("UPDATE ai_usage u LEFT JOIN credit_reservations r ON r.account_id=u.account_id AND r.request_id=CONCAT('ai_',u.request_id) SET u.status=CONCAT(IF(u.status='fallback_generated','fallback_',''),IF(r.status='sent','sent','send_unknown')) WHERE u.status IN ('generated','fallback_generated')"+(account?' AND u.account_id=?':''),params);}
export function selectUsageRequestIdByAccountIdRequestId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT request_id FROM ai_usage WHERE account_id=? AND request_id=?',params);}
export function selectAssistantsByAccountIdSessionIdProfileType(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT a.enabled,p.*,p.id AS data_profile_id FROM ai_assistants a JOIN ai_data_profiles p ON p.id=a.data_profile_id AND p.account_id=a.account_id JOIN ai_profile_types t ON t.id=p.profile_type AND t.enabled=TRUE WHERE a.account_id=? AND a.session_id=? AND p.profile_type=?',params);}
export function lockConversationForMessage(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT paused,messages,revision,router_context FROM ai_conversations WHERE account_id=? AND session_id=? AND customer=? FOR UPDATE',params);}
export function selectFallbacksIdQuestionByAccountIdSessionIdCustomer(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,question FROM ai_fallbacks WHERE account_id=? AND session_id=? AND customer=? AND status=\'waiting\' ORDER BY created_at DESC LIMIT 5',params);}
export function insertMessageUsage(c:Executor,params:SqlValue[]){return c.execute("INSERT INTO ai_usage(account_id,request_id,session_id,customer,status,input_words,input_rate,output_rate,reserved,model,profile_type,data_profile_id) VALUES (?,?,?,?,'generating',?,?,?,?,?,?,?)",params);}
export function selectConversationsPausedRevisionByAccountIdSessionIdCustomer(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT paused,revision FROM ai_conversations WHERE account_id=? AND session_id=? AND customer=?',params);}
export function insertTraceLog(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_trace_log(account_id,session_id,request_id,profile_type,node,state,model,attempt,duration_ms,input,output,error) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',params);}
export function insertAgentFailures(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO ai_agent_failures(account_id,session_id,request_id,agent,error,message,model,prompt,raw_output,router_context) VALUES (?,?,?,?,?,?,?,?,?,?)',params);}
export function finishMessageUsage(c:Executor,params:SqlValue[]){return c.execute("UPDATE ai_usage SET status=?,output_words=?,charged=?,agent=?,model_calls=?,model=?,reserved=0 WHERE account_id=? AND request_id=?",params);}
export function insertIgnoreFallbacks(c:Executor,params:SqlValue[]){return c.execute('INSERT IGNORE INTO ai_fallbacks(id,account_id,session_id,customer,fallback_number,agent,reason,question,router_context,messages,source_message_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)',params);}
export function updateFallbacksConfirmationMessageIdById(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_fallbacks SET confirmation_message_id=? WHERE id=?',params);}
export function updateFallbacksNotificationMessageIdById(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_fallbacks SET notification_message_id=? WHERE id=?',params);}
export function markFallbackFailed(c:Executor,params:SqlValue[]){return c.execute("UPDATE ai_fallbacks SET status='failed' WHERE id=?",params);}
export function updateUsageStatus(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_usage SET status=? WHERE account_id=? AND request_id=?',params);}
export function lockConversationsMessagesRevisionByAccountIdSessionIdCustomer(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT messages,revision FROM ai_conversations WHERE account_id=? AND session_id=? AND customer=? FOR UPDATE',params);}
export function updateConversationMemoryAndContext(c:Executor,params:SqlValue[]){return c.execute('UPDATE ai_conversations SET messages=?,router_context=? WHERE account_id=? AND session_id=? AND customer=?',params);}
