// SQL of this component, one named query per statement. Domain code passes the executor: the pool,
// or the connection of a transaction it has opened.
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import type {Executor,SqlValue} from '../../../libraries/db.js';
export function lockAutoShareJobsByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM auto_share_jobs WHERE account_id=? AND id=? FOR UPDATE',params);}
export function selectAutoShareRunsIdByAccountIdJobId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>("SELECT id FROM auto_share_runs WHERE account_id=? AND job_id=? AND status IN ('queued','running') LIMIT 1",params);}
export function selectAutoShareRunsIdByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>("SELECT id FROM auto_share_runs WHERE account_id=? AND status IN ('queued','running') LIMIT 32",params);}
export function selectAllContacts(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM daftar_kontak WHERE account_id=?',params);}
export function shareAutoShareTemplatesByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM auto_share_templates WHERE account_id=? AND id=? FOR SHARE',params);}
export function insertAutoShareRun(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO auto_share_runs(id,account_id,job_id,job_name,template_id,template_name,session_id,message,source,media_type,asset_id,filename,source_data,tidied,tidy_note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',params);}
export function updateAutoShareJobsRotationIndexById(c:Executor,params:SqlValue[]){return c.execute('UPDATE auto_share_jobs SET rotation_index=? WHERE id=?',params);}
export function insertAutoShareDelivery(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO auto_share_deliveries(id,run_id,nomor,position) VALUES (?,?,?,?)',params);}
export function selectAutoShareTemplatesByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,message,media_type,media_source,media_variable,source_mode,source_endpoint,source_secret,tidy,tidy_note FROM auto_share_templates WHERE account_id=? AND id=?',params);}
export function selectWalletsMaxShareAssetsMaxShareStorageBytesByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT p.max_share_assets,p.max_share_storage_bytes FROM wallets w JOIN plans p ON p.id=w.plan_id WHERE w.account_id=?',params);}
export function selectShareAssetsByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,filename,mimetype,media_type,size_bytes,created_at,public_token FROM share_assets WHERE account_id=? AND run_id IS NULL ORDER BY created_at DESC',params);}
export function countShareAssetsByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT COUNT(*) AS count, COALESCE(SUM(size_bytes),0) AS bytes FROM share_assets WHERE account_id=? AND run_id IS NULL',params);}
export function selectAutoShareTemplatesIdByAccountIdAssetId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM auto_share_templates WHERE account_id=? AND asset_id=?',params);}
export function selectShareAssetsIdByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM share_assets WHERE account_id=? AND id=?',params);}
export function deleteShareAssetsByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('DELETE FROM share_assets WHERE account_id=? AND id=?',params);}
export function selectContactsSorted(c:Executor,params:SqlValue[]){return c.execute('SELECT id,nomor,nama,kelompkontak FROM daftar_kontak WHERE account_id=? ORDER BY kelompkontak,nama,nomor',params);}
export function selectDaftarKontakIdByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM daftar_kontak WHERE account_id=? AND id=?',params);}
export function updateDaftarKontakNomorByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('UPDATE daftar_kontak SET nomor=?,nama=?,kelompkontak=? WHERE account_id=? AND id=?',params);}
export function insertDaftarKontak(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO daftar_kontak(id,account_id,nomor,nama,kelompkontak) VALUES (?,?,?,?,?)',params);}
export function deleteDaftarKontakByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('DELETE FROM daftar_kontak WHERE account_id=? AND id=?',params);}
export function selectAutoShareSettingsAutoAddEnabledByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT auto_add_enabled FROM auto_share_settings WHERE account_id=?',params);}
export function upsertAutoShareSettings(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO auto_share_settings(account_id,auto_add_enabled) VALUES (?,?) ON DUPLICATE KEY UPDATE auto_add_enabled=VALUES(auto_add_enabled)',params);}
export function lockAccountsIdById(c:Executor,params:SqlValue[]){return c.execute('SELECT id FROM accounts WHERE id=? FOR UPDATE',params);}
export function selectAutoShareTemplatesByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,name,message,media_type,asset_id,filename,source_mode,source_endpoint,media_source,media_variable,tidy,tidy_note,source_secret FROM auto_share_templates WHERE account_id=? ORDER BY created_at DESC',params);}
export function shareShareAssetsFilenameMediaTypeByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT filename,media_type FROM share_assets WHERE account_id=? AND id=? FOR SHARE',params);}
export function lockAutoShareTemplatesSourceEndpointSourceSecretByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT source_endpoint,source_secret FROM auto_share_templates WHERE account_id=? AND id=? FOR UPDATE',params);}
export function updateAutoShareTemplatesNameByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('UPDATE auto_share_templates SET name=?,message=?,media_type=?,asset_id=?,filename=?,source_mode=?,source_endpoint=?,source_secret=?,media_source=?,media_variable=?,tidy=?,tidy_note=? WHERE account_id=? AND id=?',params);}
export function insertAutoShareTemplates(c:Executor,params:SqlValue[]){return c.execute("INSERT INTO auto_share_templates(id,account_id,name,message,media_type,asset_id,filename,source_mode,source_endpoint,source_secret,media_source,media_variable,tidy,tidy_note,session_id,contacts,groups_json,content_migrated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,'',JSON_ARRAY(),JSON_ARRAY(),TRUE)",params);}
export function selectAutoShareTemplatesSourceEndpointSourceSecretByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT source_endpoint,source_secret FROM auto_share_templates WHERE account_id=? AND id=?',params);}
export function selectAutoShareJobsTemplateIdsByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT template_ids FROM auto_share_jobs WHERE account_id=?',params);}
export function deleteAutoShareTemplatesByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('DELETE FROM auto_share_templates WHERE account_id=? AND id=?',params);}
export function selectAutoShareJobsByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM auto_share_jobs WHERE account_id=? ORDER BY created_at DESC',params);}
export function selectDaftarKontakIdKelompkontakByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id,kelompkontak FROM daftar_kontak WHERE account_id=?',params);}
export function selectAutoShareTemplatesIdByAccountId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT id FROM auto_share_templates WHERE account_id=?',params);}
export function updateAutoShareJobsNameByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('UPDATE auto_share_jobs SET name=?,session_id=?,contacts=?,groups_json=?,template_ids=?,rotation_index=?,enabled=?,next_at=?,interval_minutes=? WHERE account_id=? AND id=?',params);}
export function insertAutoShareJobs(c:Executor,params:SqlValue[]){return c.execute('INSERT INTO auto_share_jobs(name,session_id,contacts,groups_json,template_ids,rotation_index,enabled,next_at,interval_minutes,account_id,id) VALUES (?,?,?,?,?,?,?,?,?,?,?)',params);}
export function deleteAutoShareJobsByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('DELETE FROM auto_share_jobs WHERE account_id=? AND id=?',params);}
export function selectAutoShareJobsByAccountIdId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>('SELECT * FROM auto_share_jobs WHERE account_id=? AND id=?',params);}
export function selectAutoShareRunsByAccountId(c:Executor,params:SqlValue[]){return c.execute(`SELECT r.*,COUNT(d.id) AS total,SUM(d.status='sent') AS sent,SUM(d.status='failed') AS failed,SUM(d.status='unknown') AS unknown_count FROM auto_share_runs r LEFT JOIN auto_share_deliveries d ON d.run_id=r.id WHERE r.account_id=? GROUP BY r.id ORDER BY r.created_at DESC LIMIT 100`,params);}
export function selectAutoShareDeliveriesByAccountIdId(c:Executor,params:SqlValue[]){return c.execute('SELECT d.* FROM auto_share_deliveries d JOIN auto_share_runs r ON r.id=d.run_id WHERE r.account_id=? AND r.id=? ORDER BY d.position',params);}
export function selectAutoShareJobsIdAccountId(c:Executor){return c.query<RowDataPacket[]>('SELECT t.id,t.account_id FROM auto_share_jobs t JOIN accounts a ON a.id=t.account_id WHERE t.enabled=TRUE AND t.next_at<=UTC_TIMESTAMP(3) AND a.suspended=FALSE ORDER BY t.next_at LIMIT 100');}
export function insertFailedScheduleRun(c:Executor,params:SqlValue[]){return c.execute("INSERT INTO auto_share_runs(id,account_id,job_id,job_name,template_id,template_name,session_id,message,source,status,finished_at) VALUES (?,?,?,?,?,?,?,?,'schedule','failed',UTC_TIMESTAMP(3))",params);}
export function insertFailedDelivery(c:Executor,params:SqlValue[]){return c.execute("INSERT INTO auto_share_deliveries(id,run_id,nomor,position,status,error) VALUES (?,?,?,0,'failed',?)",params);}
export function updateAutoShareJobsNextAtById(c:Executor,params:SqlValue[]){return c.execute('UPDATE auto_share_jobs SET next_at=?,enabled=? WHERE id=?',params);}
export function markRunRunning(c:Executor,params:SqlValue[]){return c.execute("UPDATE auto_share_runs SET status='running' WHERE id=?",params);}
export function selectAutoShareDeliveriesByRunId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>("SELECT * FROM auto_share_deliveries WHERE run_id=? AND status='pending' ORDER BY position",params);}
export function markDeliverySending(c:Executor,params:SqlValue[]){return c.execute("UPDATE auto_share_deliveries SET status='sending' WHERE id=?",params);}
export function markDeliverySent(c:Executor,params:SqlValue[]){return c.execute("UPDATE auto_share_deliveries SET status='sent',message_id=? WHERE id=?",params);}
export function updateDeliveryResult(c:Executor,params:SqlValue[]){return c.execute('UPDATE auto_share_deliveries SET status=?,error=? WHERE id=?',params);}
export function selectAutoShareDeliveriesIdByRunId(c:Executor,params:SqlValue[]){return c.execute<RowDataPacket[]>("SELECT id FROM auto_share_deliveries WHERE run_id=? AND status IN ('pending','sending') LIMIT 1",params);}
export function markRunQueued(c:Executor,params:SqlValue[]){return c.execute("UPDATE auto_share_runs SET status='queued' WHERE id=?",params);}
export function updateAutoShareRunsStatusByRunId(c:Executor,params:SqlValue[]){return c.execute("UPDATE auto_share_runs SET status=IF(EXISTS(SELECT 1 FROM auto_share_deliveries WHERE run_id=? AND status<>'sent'),'completed_with_errors','completed'),finished_at=UTC_TIMESTAMP(3) WHERE id=?",params);}
export function selectAutoShareRuns(c:Executor){return c.query<RowDataPacket[]>("SELECT * FROM auto_share_runs WHERE status='queued' ORDER BY created_at LIMIT 1");}
export function updateAutoShareDeliveriesStatus(c:Executor){return c.query("UPDATE auto_share_deliveries d JOIN auto_share_runs r ON r.id=d.run_id LEFT JOIN outbound_results o ON o.account_id=r.account_id AND o.request_id=CONCAT('share_',d.id) SET d.status=IF(o.message_id IS NULL,'unknown','sent'),d.message_id=o.message_id,d.error=IF(o.message_id IS NULL,'Proses terhenti; hasil belum pasti dan tidak dikirim ulang.',NULL) WHERE d.status='sending'");}
export function updateAutoShareRunsStatus(c:Executor){return c.query("UPDATE auto_share_runs SET status='queued' WHERE status='running'");}
export function insertIgnoreDaftarKontak(c:Executor,params:SqlValue[]){return c.execute<ResultSetHeader>('INSERT IGNORE INTO daftar_kontak(id,account_id,nomor,nama,kelompkontak) VALUES (?,?,?,?,?)',params);}
